menu:
  Docs: /docs/
  API: /api/

doc_sidebar:
  Getting Started:
    Overview: index.html
    How it works: how_it_works.html
  Shapes:
    Rect: shape_rect.html
    Circle: shape_circle.html

google_analytics:
fb_admins:
swiftype_key:
twitter: lavrton
github: konvajs/konva
