menu:
  Docs: /docs/
  API: /api/

doc_sidebar:
  Getting Started:
    Overview: index.html
    How it works: how_it_works.html
  Shapes:
    Rect : shapes/Rect.html
    Circle : shapes/Circle.html
    Ellipse : shapes/Ellipse.html
    Wedge : shapes/Wedge.html
    Line - Simple Line : shapes/Line_-_Simple_Line.html
    Line - Polygon : shapes/Line_-_Polygon.html
    Line - Spline : shapes/Line_-_Spline.html
    Line - Blob : shapes/Line_-_Blob.html
    Sprite : shapes/Sprite.html
    Image : shapes/Image.html
    Text : shapes/Text.html
    TextPath : shapes/TextPath.html
    Star : shapes/Star.html
    Label : shapes/Label.html
    Path : shapes/Path.html
    RegularPolygon : shapes/RegularPolygon.html
    Custom : shapes/Custom.html
  Styling:
    Fill : styling/Fill.html
    Stroke : styling/Stroke.html
    Opacity : styling/Opacity.html
    Shadow : styling/Shadow.html
    Line Join : styling/Line_Join.html
    Hide and Show : styling/Hide_and_Show.html
  Events:
    Binding Events : events/Binding_Events.html
    Image Events : events/Image_Events.html
    Mobile Events : events/Mobile_Events.html
    Multi Event : events/Multi_Event.html
    Desktop and Mobile : events/Desktop_and_Mobile.html
    Remove Event : events/Remove_Event.html
    Remove by Name : events/Remove_by_Name.html
    Custom Hit Region : events/Custom_Hit_Region.html
    Listen for Events : events/Listen_for_Events.html
    Cancel Propagation : events/Cancel_Propagation.html
    Event Delegation : events/Event_Delegation.html
    Fire Events : events/Fire_Events.html
  Drag and Drop:
    Drag and Drop : drag_and_Drop/Drag_and_Drop.html
    Drag an Image : drag_and_Drop/Drag_an_Image.html
    Drag a Group : drag_and_Drop/Drag_a_Group.html
    Drag a Line : drag_and_Drop/Drag_a_Line.html
    Drag a Stage : drag_and_Drop/Drag_a_Stage.html
    Drag Events : drag_and_Drop/Drag_Events.html
    Simple Drag Bounds : drag_and_Drop/Simple_Drag_Bounds.html
    Complex Drag and Drop : drag_and_Drop/Complex_Drag_and_Drop.html
    Drop Events : drag_and_Drop/Drop_Events.html
  Groups and Layers:
    Groups : groups_and_Layers/Groups.html
    Layering : groups_and_Layers/Layering.html
    Change_Containers : groups_and_Layers/Change_Containers.html
    Clipping_Regions : groups_and_Layers/Clipping_Regions.html
  Filters:
    Invert : filters/Invert.html
    Grayscale : filters/Grayscale.html
    Brighten : filters/Brighten.html
    Kaleidoscope : filters/Kaleidoscope.html
    Blur : filters/Blur.html
  Tweens:
    Linear Easing : tweens/Linear_Easing.html
    Common Easings : tweens/Common_Easings.html
    All Easings : tweens/All_Easings.html
    Finish Event : tweens/Finish_Event.html
    All Controls : tweens/All_Controls.html
    Tween Filter : tweens/Tween_Filter.html
    GreenSock Plugin : tweens/GreenSock_Plugin.html
  Animations:
    Create_an_Animation : animations/Create_an_Animation.html
    Moving : animations/Moving.html
    Rotation  : animations/Rotation .html
    Scaling : animations/Scaling.html
    Stop_Animation : animations/Stop_Animation.html
  Selectors:
    Select by id : selectors/Select_by_id.html
    Select by Type : selectors/Select_by_Type.html
    Select by Name : selectors/Select_by_Name.html
  Data & Serialization:
    Select_by_id : data_&_serialization/Select_by_id.html
    Serialize_a_Stage : data_&_serialization/Serialize_a_Stage.html
    Simple_Load : data_&_serialization/Simple_Load.html
    Complex_Load : data_&_serialization/Complex_Load.html
  Performance:
    Layer Management : performance/Layer_Management.html
    Batch Draw : performance/Batch_Draw.html
    Shape Caching : performance/Shape_Caching.html
  Sandbox:
    Zoom Layer On hover : sandbox/Zoom_Layer_On_hover.html
    Wheel of Fortune : sandbox/Wheel of Fortune.html
    Quantum_Squiggle : sandbox/Quantum_Squiggle.html
    20000_Nodes : sandbox/20000_Nodes.html
    Elastic_Stars : sandbox/Elastic_Stars.html
    Shape_Tango : sandbox/Shape_Tango.html
    Multi-touch_Scale_Shape : sandbox/Multi-touch_Scale_Shape.html
    Multi-touch_Scale_Stage : sandbox/Multi-touch_Scale_Stage.html
    Interactive_Building_Map : sandbox/Interactive_Building_Map.html
    Modify_Curves_with_Anchor_Points : sandbox/Modify_Curves_with_Anchor_Points.html
    Drag_and_Drop_Stress_Test : sandbox/Drag_and_Drop_Stress_Test.html
    Animals_on_the_Beach_Game : sandbox/Animals_on_the_Beach_Game.html
    Animation_Stress_Test : sandbox/Animation_Stress_Test.html
    10000_Shapes_with_Tooltips : sandbox/10000_Shapes_with_Tooltips.html
    Modify_Shape_Color_on_Click : sandbox/Modify_Shape_Color_on_Click.html
    Physics_Simulator : sandbox/Physics_Simulator.html
    Expand_Images_on_Hover : sandbox/Expand_Images_on_Hover.html
    Planets_Image_Map : sandbox/Planets_Image_Map.html
    Image_Resize : sandbox/Image_Resize.html
    Shape_Tooltips : sandbox/Shape_Tooltips.html
    Star_Spiner : sandbox/Star_Spiner.html
    Drag_and_Drop_Multiple_Shapes : sandbox/Drag_and_Drop_Multiple_Shapes.html
    Image_Border_Highlighting : sandbox/Image_Border_Highlighting.html

google_analytics: UA-54202824-2
fb_admins:
swiftype_key:
twitter: lavrton
github: konvajs/konva
